### ISSUE TITLE
Enhancement: Replace hard coded fading with CSS mask

### ISSUE THREAD

**Issue by Tom-Hirschberger** [fewieden/MMM-Fuel#101]
Hi,

a user asked of how to remove the fading of the table content in the forum today.
I saw that you hard coded the opacity settings as style to the nunjucks template while i investigated the problem.
So there is no easy way for "normal" users to configure the fading as even if something else is set in the "custom.css" the values get ignored as there are values set to the elements directly.

Maybe you can think about a change to CSS masks instead. If the opacity settings are removed of the "tr" elements something like:
```CSS
.MMM-Fuel .module-content{
  mask-image: linear-gradient(180deg, rgb(0, 0, 0), transparent 110%);
  -webkit-mask-image: -webkit-linear-gradient(270deg, rgb(0, 0, 0), transparent 110%);
}
```

will have the same effect. 
I tested it with the current Chromium and Firefox version. With the currently used electron version it is working well, too.
